---
- name: AWS Deploy
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/sts.yml
    - vars/default.yml
  tasks:
    - name: AWS Get STS Credentials
      local_action:
        module: sts_assume_role
        profile: "{{sts_profile}}"
        region: "{{region}}"
        role_arn: "{{sts_role_arn}}"
        role_session_name: "{{sts_role_session_name}}"
      register: assumed_role
      when: sts

    - name: Retreive STS Credentials
      set_fact:
        sts_aws_access_key: "{{ hostvars['localhost']['assumed_role'].sts_creds.access_key }}"
        sts_aws_secret_key: "{{ hostvars['localhost']['assumed_role'].sts_creds.secret_key }}"
      when: sts

    - name: AWS Create Security Group
      local_action:
        module: ec2_group
        aws_access_key: "{{ sts_aws_access_key | default(omit) }}"
        aws_secret_key: "{{ sts_aws_secret_key | default(omit) }}"
        name: "{{sg_name}}"
        description: "{{sg_name}} - Created by Ansible"
        vpc_id: "{{vpc_id}}"
        region: "{{region}}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: sg
