---
aws_access: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
aws_secret: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"

region: "us-east-2"
sg_name: "test-sg" # Name for new AWS Security Group
vpc_id: "vpc-XXXXXXXX" # Existing VPCID from your account
